import { Task } from "../../domain/entities/Task.js";

export enum TASK_STATUS {
  NEW = 'NEW',
  IN_PROGRESS = 'IN_PROGRESS',
  ASSIGNED = 'ASSIGNED',
  COMPLETED = 'COMPLETED',
}

export const EVENT_TYPE = {
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_CONNECTED: 'USER_CONNECTED',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_ASSIGNED_USER_ID: 'TASK_ASSIGNED_USER_ID',
  TASK_NEW: 'TASK_NEW',
  TASK_IN_PROGRESS: 'TASK_IN_PROGRESS',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_UNCOMPLETED: 'TASK_UNCOMPLETED',
  TASK_DELETED: 'TASK_DELETED',
  BOARD_CREATED: 'BOARD_CREATED',
  BOARD_UPDATED: 'BOARD_UPDATED',
  BOARD_ASSIGNED: 'BOARD_ASSIGNED',
  BOARD_MEMBER_ADDED: 'BOARD_MEMBER_ADDED',
  BOARD_MEMBER_REMOVED: 'BOARD_MEMBER_REMOVED',
};

export interface TaskEvent {
  eventType: typeof EVENT_TYPE;
  task: Task;
}